#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export CUSTOM_BIN=$HOME/Documents/Dropbox/scripts/bash
export PATH=$CUSTOM_BIN:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:$PATH

# bluetooth handling
source $HOME/.zprezto/custom/turn_bluetooth_device.sh
alias stanny_up='turn_bt_device $BT_STANNY on'
alias stanny_down='turn_bt_device $BT_STANNY off'


# make directory color brighter
export LSCOLORS='ExGxBxDxCxEgEdxbxgxcxd' # ls colors like in Linux
export LS_COLORS='di=1;36:ln=1;35:so=1;31:pi=1;33:ex=1;32:bd=1;34;46:cd=1;34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43'
zstyle ':completion:*:default' list-colors "$LS_COLORS"

alias ll='ls -al'
alias apt-upgrade='sudo apt update && sudo apt upgrade && sudo apt autoremove'
alias sys='systemctl --user'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

